---

- name: MRBS | Packages
  package: name={{ item }} 
  with_items: "{{ mrbs_packages }}"

- name: MRBS | Download
  get_url:
    url: "{{ mrbs_source_url }}"
    dest: "{{ mrbs_base_dir }}/mrbs-{{ mrbs_version }}.tar.gz"
  register: mrbs_download

- name: MRBS | Unarchive
  unarchive: 
    src: "{{ mrbs_base_dir }}/mrbs-{{ mrbs_version }}.tar.gz"
    dest: "{{ mrbs_base_dir }}"
    remote_src: True
  when: mrbs_download.changed

- name: MRBS | Dir ownership and permissions
  file: 
    path: "{{ mrbs_base_dir }}/{{ mrbs_dir_name }}"
    owner: "{{ mrbs_dir_owner }}"
    group: "{{ mrbs_dir_group }}"
    mode: "{{ mrbs_dir_mode }}"