---

- name: MRBS | Packages
  package: name={{ item }} 
  with_items: "{{ mrbs_packages }}"

- name: MRBS | Download
  get_url:
    url: "{{ mrbs_source_url }}"
    dest: "{{ mrbs_base_dir }}"
  register: mrbs_files

- name: MRBS | Unarchive
  unarchive: 
    src: "{{ mrbs_base_dir }}/{{ item }}"
    dest: "{{ mrbs_base_dir }}/{{ mrbs_dir_name }}"
    copy: no
  with_items:
    - "{{ mrbs_files.stdout }}"

- name: MRBS | Dir ownership and permissions
  file: 
    path: "{{ mrbs_base_dir }}/{{ mrbs_dir_name }}"
    owner: "{{ mrbs_dir_owner }}"
    group: "{{ mrbs_dir_group }}"
    mode: "{{ mrbs_dir_mode }}"