---
# tasks file for ansible-role-mrbs

- include_tasks: install.yml

- include_tasks: mysql_config.yml
  when: mrbs_db_system == "mysql"

- include_tasks: mrbs_config.yml

- include_tasks: shibb_auth_config.yml
  when: mrbs_shibb_auth | bool


