---

- name: MRBS | mrbs config inc php
  template: 
    src: "config.inc.php.j2"
    dest: "{{ mrbs_base_dir }}/{{ mrbs_dir_name }}/config.inc.php"
    owner: "{{ mrbs_dir_owner }}"
    group: "{{ mrbs_dir_group }}"